# Site settings
title: LiftForward Tech Blog
email: engineering@liftforward.com
description: "Musings of the LiftForward engineering team on Ember JS, Ruby and other stuff"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tech.liftforward.com" # the base hostname & protocol for your site
twitter_username: liftforward
github_username:  liftforward

# Build settings
markdown: kramdown

kramdown:
  input: GFM