# Site settings
title: LiftForward Tech Blog
email: engineering@liftforward.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tech.liftforward.com" # the base hostname & protocol for your site
twitter_username: liftforward
# github_username:  drewnichols

# Build settings
markdown: kramdown

kramdown:
  input: GFM